# Generated by Django 3.2.14 on 2022-07-20 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание ИТ актива')),
                ('description', models.TextField(verbose_name='Описание функционала')),
                ('allocation', django_editorjs.fields.EditorJsField(verbose_name='Размещение')),
                ('instances', django_editorjs.fields.EditorJsField(verbose_name='Сервера/инстансы')),
                ('ipscope', django_editorjs.fields.EditorJsField(verbose_name='Адресное пространство')),
                ('relations', django_editorjs.fields.EditorJsField(verbose_name='Зависимости ПО и версии')),
                ('settings', django_editorjs.fields.EditorJsField(verbose_name='Текущие настройки')),
                ('components', django_editorjs.fields.EditorJsField(verbose_name='Компоненты системы')),
                ('management', django_editorjs.fields.EditorJsField(verbose_name='Порядок управления')),
                ('access', django_editorjs.fields.EditorJsField(verbose_name='Порядок доступа')),
                ('userlist', django_editorjs.fields.EditorJsField(verbose_name='Учетные записи')),
                ('regulations', django_editorjs.fields.EditorJsField(verbose_name='Регламентные действия')),
                ('additional_info', django_editorjs.fields.EditorJsField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('slug', models.SlugField(unique=True, verbose_name='URL идентификатор')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itasset', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ИТ Актив',
                'verbose_name_plural': 'ИТ актив',
                'ordering': ('-created',),
            },
        ),
    ]
