# Generated by Django 3.2.14 on 2022-07-19 18:12

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systopology',
            name='body',
        ),
        migrations.AddField(
            model_name='systopology',
            name='allocation',
            field=django_editorjs.fields.EditorJsField(default=0, verbose_name='Размещение'),
            preserve_default=False,
        ),
    ]
