# Generated by Django 3.2.14 on 2022-08-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_file', models.FileField(upload_to='itasset/uploads/', verbose_name='Файл')),
                ('description', models.TextField(verbose_name='Содержание файла')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='itasset.itasset', verbose_name='Приложение')),
            ],
        ),
    ]
