# Generated by Django 3.2.14 on 2022-08-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0003_auto_20220801_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itassetfile',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='itasset.itasset', verbose_name='Приложение'),
        ),
    ]
