# Generated by Django 3.2.14 on 2022-08-08 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itasset', '0005_itassetfile_secured_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itassetfile',
            name='secured_users',
        ),
        migrations.AddField(
            model_name='itasset',
            name='secured_users',
            field=models.ManyToManyField(related_name='secured_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
