# Generated by Django 3.2.14 on 2022-07-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itasset', '0005_auto_20220721_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itasset', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
