# Generated by Django 3.2.14 on 2022-07-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0006_alter_itasset_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL идентификатор')),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('image', models.ImageField(blank=True, upload_to='itasset/group', verbose_name='Баннер группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='itasset',
            name='image',
            field=models.ImageField(blank=True, upload_to='itasset/assets/', verbose_name='Баннер актива'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться актив', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itasset', to='itasset.itassetgroup', verbose_name='Группа активов'),
        ),
    ]
