# Generated by Django 3.2.14 on 2022-08-08 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itasset', '0007_alter_itasset_secured_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='secured_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='secured_assets', to=settings.AUTH_USER_MODEL, verbose_name='Доверенные пользователи'),
        ),
    ]
