# Generated by Django 3.2.14 on 2022-07-23 09:36

from django.db import migrations, models
import itasset.models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0007_auto_20220722_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование актива'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='userlist',
            field=itasset.models.SecureCharField(blank=True, verbose_name='Учетные записи'),
        ),
    ]
