# Generated by Django 3.2.14 on 2022-07-23 11:21

from django.db import migrations
import itasset.models


class Migration(migrations.Migration):

    dependencies = [
        ('itasset', '0008_auto_20220723_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='userlist',
            field=itasset.models.SecureCharField(blank=True, max_length=1024, verbose_name='Учетные записи'),
        ),
    ]
